=== JuantonioMS/biohub/biohub/conf/core/schemas/apps.json
{
    "$id" : "https://example.com/demo",
    "$schema" : "https://json-schema.org/draft/2020-12/schema",

    "title" : "JSON schema BioHub apps",
    "description" : "JSON schema for apps json files validation.",

    "type" : "object",
    "additionalProperties": false,
    "properties" :
    {



        "info" :
        {
            "description" : "Process info section",
            "type" : "object",
            "required" : ["type"],
            "additionalProperties": false,
            "properties" :
            {

                "type" :
                {
                    "description" : "Type of process. BioHub can handle conda, singularity and raw-system processes",
                    "type" : "string",
                    "enum" : ["conda", "singularity", "system"]
                },

                "environment" :
                {
                    "description" : "type==conda -> conda env name; type==singularity -> image name",
                    "type" : "string"
                },

                "description" :
                {
                    "description" : "Short process description",
                    "type" : "string"
                }

            }
        },



        "build" :
        {
            "description" : "Instructions for process build-up",
            "type" : "array",
            "items" :
            {
                "description" : "CLI command",
                "type" : "string"
            }
        },



        "implementation" :
        {
            "description" : "Process execution info",
            "type" : "object",
            "required" : ["commands", "sentences"],
            "additionalProperties": false,
            "properties" :
            {

                "defaultRoute" :
                {
                    "description" : "Process default route, if not setted, default 'common'",
                    "type" : "string"
                },

                "commands" :
                {
                    "description" : "",
                    "type" : "array",
                    "items" :
                    {
                        "description" : "",
                        "type" : "object",
                        "required" : ["route", "command"],
                        "additionalProperties": false,
                        "properties" :
                        {

                            "route" :
                            {
                                "description" : "",
                                "type" : "string"
                            },

                            "command" :
                            {
                                "description" : "",
                                "type" : "string"
                            }

                        }
                    }
                },

                "sentences" :
                {
                    "description" : "",
                    "type" : "object",
                    "required" : ["body"],
                    "additionalProperties": false,
                    "properties" :
                    {

                        "head" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        },

                        "body" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        },

                        "tail" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        }

                    }
                }

            }
        },



        "options" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "name"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "value" :
                    {
                        "description" : "",
                        "type" : ["string", "number", "boolean"]
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "inputs" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "selection"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "selection" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "object",
                            "required" : ["target", "required"],
                            "additionalProperties" : false,
                            "properties" :
                            {

                                "target" :
                                {
                                    "description" : "",
                                    "type" : "string",
                                    "enum" : ["outlines", "tags", "extension", "tool"]
                                },

                                "required" :
                                {
                                    "description" : "",
                                    "type" : ["string", "array"]
                                },

                                "optimal" :
                                {
                                    "description" : "",
                                    "type" : ["string", "array"]
                                }

                            }
                        }
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "outputs" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "temporal", "extension"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "temporal" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "extension" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "outlines" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "outlines" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "process" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    },

                    "output" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    }

                }
            }
        }



    }
}

=== JuantonioMS/biohub/biohub/conf/apps/taxonomicprofiling/krakenuniq.json
{
    "info" :
    {
        "type" : "conda",
        "environment": "biohub.krakenuniq"
    },



    "build":
    [
        "mamba create -y -p ->eval##self.environment<- krakenuniq"
    ],



    "implementation" :
    {

        "defaultRoute": "paired illumina",

        "commands": [
            {
                "route": "common",
                "command": "kraken2"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "paired illumina",
                    "sentences" : ["<command> <options> <outputs> ->eval##inputs['database']<- ->eval##inputs['forward']<- ->eval##inputs['reverse']<-"]
                }
            ]

        }
    },



    "options": [

        {
            "route" : "common",
            "role" : "threads",
            "name" : "--threads"
        },

        {
            "route" : "common",
            "role" : "preload memory size",
            "name" : "--preload-size",
            "value" : "->eval##str(int(self.memoryPerTask[:-1) - 1) + 'G'<-"
        },

        {
            "route" : "paired illumina",
            "role" : "paired file flag",
            "name" : "--paired",
            "value" : true
        }

    ],



    "inputs" :
    [

        {
            "route" : "common",
            "role" : "database",
            "name" : "--db",
            "selection" :
            [
                {
                    "target" : "outlines",
                    "required" : ["metagenomic", "database"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "forward",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "forward", "no host"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "reverse",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse", "no host"]
                }
            ]
        }
    ],



    "outputs" :
    [
        {
            "route": "common",
            "role": "reads classification",
            "name": "--report-file",
            "temporal": "reads_classification.tsv",
            "extension": ".tsv",
            "outlines": ["reads classification"]
        },

        {
            "route": "common",
            "role": "report",
            "name": "--output",
            "temporal": "report.out",
            "extension": ".out",
            "outlines": ["report"]
        }
    ]
}

=== JuantonioMS/biohub/biohub/conf/apps/taxonomicprofiling/motus2.json
{
    "info" : {
        "type" : "conda",
        "environment": "biohub.motus2"
    },

    "build": [
        "mamba create -y -p ->eval##self.environment<- motus",
        ". ->eval##self.condaShell<- && conda activate ->eval##self.environment<- && motus downloadDB"
    ],

    "implementation" : {

        "defaultRoute": "paired illumina",

        "commands": [
            {
                "route": "common",
                "command": "motus profile"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <inputs> <outputs> <options>"]
                }
            ]

        }
    },

    "options": [

        {
            "route": "common",
            "role": "threads",
            "name": "-t"
        },

        {
            "route": "common",
            "role": "NCBI taxonomy flag",
            "name": "-p",
            "value": true
        }

    ],

    "inputs": [
        {
            "route": "paired illumina",
            "role": "forward",
            "name" : "-f",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["reads", "forward", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        },
        {
            "route": "paired illumina",
            "role": "reverse",
            "name" : "-r",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        }

    ],

    "outputs": [
        {
            "route": "common",
            "role": "output",
            "name": "-o",
            "temporal": "output.out",
            "extension": ".out",
            "outlines": ["output"]
        }
    ]
}

=== JuantonioMS/biohub/biohub/conf/apps/trimming/fastp.json
{

    "info" : {
        "type" : "conda",
        "environment": "biohub.fastp"
    },

    "build": [
        "mamba create -y -p ->eval##self.environment<- fastp"
    ],

    "implementation" : {

        "defaultRoute": "paired",

        "commands": [
            {
                "route": "common",
                "command": "fastp"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs> <outputs>"]
                }
            ]

        }
    },

    "options": [

        {
            "route": "common",
            "role": "threads",
            "name": "--thread",
            "altName": "-w"
        },

        {
            "route": "common",
            "role": "minimum quality",
            "name": "--qualified_quality_phred",
            "altName": "-q",
            "value": 20
        },

        {
            "route": "common",
            "role": "minimum length",
            "name": "--length_required",
            "altName": "-l",
            "value": 40
        }

    ],

    "inputs": [

        {
            "route": "paired",
            "role": "forward",
            "name": "--in1",
            "altName": "-i",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["reads", "forward"],
                    "optimal": ["raw"]
                }
            ]
        },

        {
            "route": "paired",
            "role": "reverse",
            "name": "--in2",
            "altName": "-I",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse"],
                    "optimal": ["raw"]
                }
            ]
        },

        {
            "route": "single",
            "role": "single",
            "name": "--in1",
            "altName": "-i",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["reads"],
                    "optimal": ["raw"]
                }
            ]
        }

    ],

    "outputs": [

        {
            "route": "paired",
            "role": "forward",
            "name": "--out1",
            "altName": "-o",
            "temporal": "forward.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["forward"]
        },

        {
            "route": "paired",
            "role": "reverse",
            "name": "--out2",
            "altName": "-O",
            "temporal": "reverse.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["reverse"]
        },

        {
            "route": "single",
            "role": "single",
            "name": "--out1",
            "altName": "-o",
            "temporal": "single.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["single"]
        },

        {
            "route": "common",
            "role": "html report",
            "name": "--html",
            "altName": "-h",
            "temporal": "fastp.html",
            "extension": ".html",
            "outlines": ["fastp html report"]
        },

        {
            "route": "common",
            "role": "json report",
            "name": "--json",
            "altName": "-j",
            "temporal": "fastp.json",
            "extension": ".json",
            "outlines": ["fastp json report"]
        }

    ],

    "outlines": [
        {
            "route": "common",
            "output": ["reads"],
            "process": ["reads"]
        }
    ]

}

=== JuantonioMS/biohub/biohub/conf/apps/annotation/amrplusplus.json
{
    "info" : {
        "type" : "singularity",
        "environment": "amrplusplus_latest.sif"
    },

    "build": [
        "singularity pull docker://enriquedoster/amrplusplus:latest",
        "mv amrplusplus_latest.sif ->eval##self.environment<-"
    ],

    "implementation" : {

        "defaultRoute": "common",

        "commands": [
            {
                "route": "common",
                "command": "nextflow run main_AMR++.nf"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs>"]
                }
            ]

        }

    },

    "options": [

        {
            "route": "common",
            "role": "outputDirectory",
            "name": "--output_file",
            "altName": "-o"
        },

        {
            "route": "common",
            "role": "threads",
            "name": "--num_threads",
            "altName": "-n"
        },

        {
            "route": "common",
            "role": "clean temporal files",
            "name": "--clean",
            "value": true
        }

    ],

    "inputs": [
        {
            "route": "common",
            "role": "genome",
            "name": "--input_sequence",
            "altName": "-i",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["genome"]
                }
            ]
        }
    ],

    "outputs": [
        {
            "route": "common",
            "role": "json format",
            "temporal": "output.json",
            "extension": ".json",
            "outlines": ["card", "json"]
        },

        {
            "route": "common",
            "role": "txt format",
            "temporal": "output.txt",
            "extension": ".txt",
            "outlines": ["card", "txt"]
        }
    ],

    "outlines": [
        {
            "route": "common",
            "output": ["resistance genes"],
            "process": ["resistance genes"]
        }
    ]
}

=== JuantonioMS/biohub/biohub/conf/apps/annotation/plasmidfinder.json
{
    "info" : {
        "type" : "conda",
        "environment": "biohub.plasmidfinder"
    },

    "build": [
        "mamba create -y -p ->eval##self.environment<- plasmidfinder"
    ],

    "implementation" : {

        "defaultRoute": "genome",

        "commands": [
            {
                "route": "common",
                "command": "plasmidfinder.py"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs>"]
                }
            ]

        }

    },

    "options": [
        {
            "route": "common",
            "role": "outputDirectory",
            "name": "--outputPath",
            "altName": "-o"
        }
    ],

    "inputs": [
        {
            "route": "genome",
            "role": "genome",
            "name": "--infile",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["genome"]
                }
            ]
        }
    ],

    "outputs": [
        {
            "route": "genome",
            "role": "plasmid hits",
            "temporal": "data.json",
            "extension": ".json"
        }
    ],

    "outlines": [
        {
            "route": "common",
            "output": ["plasmids"],
            "process": ["plasmids"]
        }
    ]
}
