=== JuantonioMS/biohub/biohub/conf/core/schemas/apps.json
{
    "$id" : "https://example.com/demo",
    "$schema" : "https://json-schema.org/draft/2020-12/schema",

    "title" : "JSON schema BioHub apps",
    "description" : "JSON schema for apps json files validation.",

    "type" : "object",
    "additionalProperties": false,
    "properties" :
    {



        "info" :
        {
            "description" : "Process info section",
            "type" : "object",
            "required" : ["type"],
            "additionalProperties": false,
            "properties" :
            {

                "type" :
                {
                    "description" : "Type of process. BioHub can handle conda, singularity and raw-system processes",
                    "type" : "string",
                    "enum" : ["conda", "singularity", "system"]
                },

                "environment" :
                {
                    "description" : "type==conda -> conda env name; type==singularity -> image name",
                    "type" : "string"
                },

                "description" :
                {
                    "description" : "Short process description",
                    "type" : "string"
                }

            }
        },



        "build" :
        {
            "description" : "Instructions for process build-up",
            "type" : "array",
            "items" :
            {
                "description" : "CLI command",
                "type" : "string"
            }
        },



        "implementation" :
        {
            "description" : "Process execution info",
            "type" : "object",
            "required" : ["commands", "sentences"],
            "additionalProperties": false,
            "properties" :
            {

                "defaultRoute" :
                {
                    "description" : "Process default route, if not setted, default 'common'",
                    "type" : "string"
                },

                "commands" :
                {
                    "description" : "",
                    "type" : "array",
                    "items" :
                    {
                        "description" : "",
                        "type" : "object",
                        "required" : ["route", "command"],
                        "additionalProperties": false,
                        "properties" :
                        {

                            "route" :
                            {
                                "description" : "",
                                "type" : "string"
                            },

                            "command" :
                            {
                                "description" : "",
                                "type" : "string"
                            }

                        }
                    }
                },

                "sentences" :
                {
                    "description" : "",
                    "type" : "object",
                    "required" : ["body"],
                    "additionalProperties": false,
                    "properties" :
                    {

                        "head" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        },

                        "body" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        },

                        "tail" :
                        {
                            "description" : "",
                            "type" : "array",
                            "items" :
                            {
                                "description" : "",
                                "type" : "object",
                                "required" : ["route", "sentences"],
                                "additionalProperties": false,
                                "properties" :
                                {

                                    "route" :
                                    {
                                        "description" : "",
                                        "type" : "string"
                                    },

                                    "sentences" :
                                    {
                                        "description" : "",
                                        "type" : "array",
                                        "items" :
                                        {
                                            "description" : "",
                                            "type" : "string"
                                        }
                                    }

                                }
                            }
                        }

                    }
                }

            }
        },



        "options" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "name"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "value" :
                    {
                        "description" : "",
                        "type" : ["string", "number", "boolean"]
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "inputs" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "selection"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "selection" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "object",
                            "required" : ["target", "required"],
                            "additionalProperties" : false,
                            "properties" :
                            {

                                "target" :
                                {
                                    "description" : "",
                                    "type" : "string",
                                    "enum" : ["outlines", "tags", "extension", "tool"]
                                },

                                "required" :
                                {
                                    "description" : "",
                                    "type" : ["string", "array"]
                                },

                                "optimal" :
                                {
                                    "description" : "",
                                    "type" : ["string", "array"]
                                }

                            }
                        }
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "outputs" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route", "role", "temporal", "extension"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "role" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "name" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "altName" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "temporal" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "extension" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "outlines" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    },

                    "condition" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "format" :
                    {
                        "description" : "",
                        "type" : "string"
                    }

                }
            }
        },



        "outlines" :
        {
            "description" : "",
            "type" : "array",
            "items" :
            {
                "description" : "",
                "type" : "object",
                "required" : ["route"],
                "additionalProperties": false,
                "properties" :
                {

                    "route" :
                    {
                        "description" : "",
                        "type" : "string"
                    },

                    "process" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    },

                    "output" :
                    {
                        "description" : "",
                        "type" : "array",
                        "items" :
                        {
                            "description" : "",
                            "type" : "string"
                        }
                    }

                }
            }
        }



    }
}

=== JuantonioMS/biohub/biohub/conf/apps/operation/humanhostreadsdepletion.json
{

    "info" : {
        "type" : "conda",
        "environment": "biohub.humanhostreadsdepletion"
    },

    "build": [
        "mamba create -y -p ->eval##self.environment<- bowtie2",
        "wget https://genome-idx.s3.amazonaws.com/bt/GRCh38_noalt_as.zip",
        "unzip GRCh38_noalt_as.zip",
        "mv GRCh38_noalt_as ->eval##self.environment<-/share/GRCh38_noalt_as"
    ],

    "implementation" : {

        "defaultRoute": "paired illumina",

        "commands": [
            {
                "route": "common",
                "command": "bowtie2"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs> > ->eval##self.temporalDirectory<-/reads.sam"]
                }
            ]

        }
    },

    "options": [

        {
            "route" : "common",
            "role" : "bowtie2 index",
            "name" : "-x",
            "value" : "->eval##self.environment<-/share/GRCh38_noalt_as"
        },

        {
            "route": "common",
            "role": "threads",
            "name": "--threads",
            "altName": "-p"
        },

        {
            "route": "paired illumina",
            "role": "unaligned reads",
            "name": "--un-conc-gz",
            "value": "unaligned"
        },

        {
            "route": "paired illumina",
            "role": "aligned reads",
            "name": "--al-conc-gz",
            "value": "aligned"
        }

    ],

    "inputs": [

        {
            "route" : "paired illumina",
            "role" : "forward",
            "name" : "-1",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "forward", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "reverse",
            "name" : "-2",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        }

    ],

    "outputs": [

        {
            "route": "paired",
            "role": "forward",
            "name": "--out1",
            "altName": "-o",
            "temporal": "forward.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["forward"]
        },

        {
            "route": "paired",
            "role": "reverse",
            "name": "--out2",
            "altName": "-O",
            "temporal": "reverse.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["reverse"]
        },

        {
            "route": "single",
            "role": "single",
            "name": "--out1",
            "altName": "-o",
            "temporal": "single.fastq.gz",
            "extension": ".fastq.gz",
            "outlines": ["single"]
        },

        {
            "route": "common",
            "role": "html report",
            "name": "--html",
            "altName": "-h",
            "temporal": "fastp.html",
            "extension": ".html",
            "outlines": ["fastp html report"]
        },

        {
            "route": "common",
            "role": "json report",
            "name": "--json",
            "altName": "-j",
            "temporal": "fastp.json",
            "extension": ".json",
            "outlines": ["fastp json report"]
        }

    ],

    "outlines": [
        {
            "route": "common",
            "output": ["reads"],
            "process": ["reads"]
        }
    ]

}

=== JuantonioMS/biohub/biohub/conf/apps/annotation/amrfinder.json
{
    "info" : {
        "type" : "conda",
        "environment": "biohub.amrfinder"
    },

    "build": [
        "mamba create -y -p ->eval##self.environment<- ncbi-amrfinderplus",
        ". ->eval##self.condaShell<- && conda activate ->eval##self.environment<- && amrfinder --update"
    ],

    "implementation" : {

        "defaultRoute": "genome",

        "commands": [
            {
                "route": "common",
                "command": "amrfinder"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs> > <outputs>"]
                }
            ]

        }

    },

    "options": [

        {
            "route": "common",
            "role": "threads",
            "name": "--threads"
        },

        {
            "route": "common",
            "role": "extended results",
            "name": "--plus",
            "value": true
        }
    ],

    "inputs": [
        {
            "route": "genome",
            "role": "genome",
            "name": "--nucleotide",
            "selection": [
                {
                    "target": "outlines",
                    "required": ["genome"]
                }
            ]
        }
    ],

    "outputs": [

        {
            "route": "genome",
            "role": "resistenace table",
            "temporal": "table.tsv",
            "extension": ".tsv"
        }

    ],

    "outlines": [
        {
            "route": "common",
            "output": ["resistance genes"],
            "process": ["resistance genes"]
        }
    ]
}

=== JuantonioMS/biohub/biohub/conf/apps/taxonomicprofiling/centrifuge.json
{
    "info" :
    {
        "type" : "conda",
        "environment": "biohub.centrifuge"
    },



    "build":
    [
        "mamba create -y -p ->eval##self.environment<- centrifuge"
    ],



    "implementation" :
    {

        "defaultRoute": "paired illumina",

        "commands": [
            {
                "route": "common",
                "command": "centrifuge"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "common",
                    "sentences" : ["<command> <options> <inputs> <outputs>"]
                }
            ]

        }
    },



    "options": [

        {
            "route" : "common",
            "role" : "threads",
            "name" : "--threads",
            "altName" : "-p"
        }

    ],



    "inputs" :
    [

        {
            "route" : "common",
            "role" : "database",
            "name" : "-x",
            "selection" :
            [
                {
                    "target" : "outlines",
                    "required" : ["metagenomic", "database"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "forward",
            "name" : "-1",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "forward", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "reverse",
            "name" : "-2",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse", "illumina", "no host"],
                    "optimal": ["trimmed"]
                }
            ]
        }
    ],



    "outputs" :
    [
        {
            "route": "common",
            "role": "report",
            "name": "--report-file",
            "temporal": "report.tsv",
            "extension": ".tsv",
            "outlines": ["report"]
        },

        {
            "route": "common",
            "role": "output",
            "name": "-S",
            "temporal": "output.out",
            "extension": ".out",
            "outlines": ["output"]
        }
    ]
}

=== JuantonioMS/biohub/biohub/conf/apps/taxonomicprofiling/kraken2.json
{
    "info" :
    {
        "type" : "conda",
        "environment": "biohub.kraken2"
    },



    "build":
    [
        "mamba create -y -p ->eval##self.environment<- kraken2"
    ],



    "implementation" :
    {

        "defaultRoute": "paired illumina",

        "commands": [
            {
                "route": "common",
                "command": "kraken2"
            }
        ],

        "sentences": {

            "body" : [
                {
                    "route" : "paired illumina",
                    "sentences" : ["<command> <options> <outputs> ->eval##inputs['database']<- ->eval##inputs['forward']<- ->eval##inputs['reverse']<-"]
                }
            ]

        }
    },



    "options": [

        {
            "route" : "common",
            "role" : "threads",
            "name" : "--threads"
        },

        {
            "route" : "paired illumina",
            "role" : "paired file flag",
            "name" : "--paired",
            "value" : true
        }

    ],



    "inputs" :
    [

        {
            "route" : "common",
            "role" : "database",
            "name" : "--db",
            "selection" :
            [
                {
                    "target" : "outlines",
                    "required" : ["metagenomic", "database"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "forward",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "forward", "no host"]
                }
            ]
        },

        {
            "route" : "paired illumina",
            "role" : "reverse",
            "selection" :
            [
                {
                    "target": "outlines",
                    "required": ["reads", "reverse", "no host"]
                }
            ]
        }
    ],



    "outputs" :
    [
        {
            "route": "common",
            "role": "reads classification",
            "name": "--report",
            "temporal": "reads_classification.tsv",
            "extension": ".tsv",
            "outlines": ["reads classification"]
        },

        {
            "route": "common",
            "role": "report",
            "name": "--output",
            "temporal": "report.out",
            "extension": ".out",
            "outlines": ["report"]
        }
    ]
}
